# Generated by Django 2.2.6 on 2019-10-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr001', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empe',
            old_name='dept',
            new_name='store',
        ),
    ]
