# Generated by Django 2.2.6 on 2019-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr001', '0003_auto_20191029_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='empe',
            name='seq2',
            field=models.IntegerField(default=0, verbose_name='序號2'),
        ),
    ]
