# Generated by Django 2.2.6 on 2019-10-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr001', '0004_empe_seq2'),
    ]

    operations = [
        migrations.AddField(
            model_name='empe',
            name='is_resign',
            field=models.BooleanField(default=False, verbose_name='是否離職'),
        ),
    ]
