# Generated by Django 2.2.6 on 2019-10-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr001', '0005_empe_is_resign'),
    ]

    operations = [
        migrations.AddField(
            model_name='empe',
            name='resigndate',
            field=models.DateField(blank=True, null=True, verbose_name='離職日期'),
        ),
        migrations.AddField(
            model_name='empe',
            name='work2date',
            field=models.DateField(blank=True, null=True, verbose_name='转正日期'),
        ),
    ]
