# Generated by Django 2.2.6 on 2019-11-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr001', '0006_auto_20191031_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('date1', models.DateField(verbose_name='調薪日期')),
                ('pay1', models.IntegerField(verbose_name='原有薪資')),
                ('pay2', models.IntegerField(verbose_name='調整后薪資')),
                ('approval', models.CharField(max_length=30, verbose_name='調資審批人')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='備註')),
                ('empe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr001.Empe')),
            ],
        ),
    ]
