# Generated by Django 2.2.6 on 2019-10-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case002', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('member', models.CharField(max_length=6)),
                ('date1', models.DateField()),
                ('role', models.CharField(max_length=32)),
            ],
        ),
    ]
