# Generated by Django 2.2.6 on 2019-10-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case002', '0002_data2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data2',
            unique_together={('name', 'date1')},
        ),
    ]
