# Generated by Django 2.2.6 on 2019-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case002', '0003_auto_20191026_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='data2',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
