# Generated by Django 2.2.6 on 2019-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case002', '0005_auto_20191027_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('title', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('date1', 'title')},
            },
        ),
    ]
