# Generated by Django 2.2.6 on 2019-10-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(unique=True, verbose_name='序號')),
                ('datefrom', models.DateField(verbose_name='開始日期')),
                ('dateto', models.DateField(verbose_name='截止日期')),
                ('rent1', models.IntegerField(verbose_name='银泰嘉园置业租金')),
                ('rent2', models.IntegerField(verbose_name='恒泽行服务费')),
                ('paid1', models.DateField(blank=True, null=True, verbose_name='租金付款日期')),
                ('paid2', models.DateField(blank=True, null=True, verbose_name='服务费付款日期')),
                ('paid1note', models.CharField(blank=True, max_length=50, null=True, verbose_name='租金付款備註')),
                ('paid2note', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务费付款備註')),
            ],
            options={
                'verbose_name': '御华里商铺',
                'verbose_name_plural': '御华里商铺',
            },
        ),
    ]
