# Generated by Django 2.2.6 on 2019-10-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(unique=True, verbose_name='序號')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('daterange', models.CharField(max_length=50, verbose_name='合同期限')),
                ('rental', models.CharField(max_length=50, verbose_name='房租价格')),
                ('paid', models.CharField(max_length=50, verbose_name='已支付月份')),
                ('deposit', models.CharField(max_length=50, verbose_name='保证金/押金')),
                ('paymethod', models.CharField(default='---', max_length=50, verbose_name='付款方式')),
                ('area', models.CharField(max_length=50, verbose_name='面积')),
                ('usage', models.CharField(max_length=50, verbose_name='用途')),
                ('addr', models.CharField(max_length=300, verbose_name='地址')),
                ('note', models.CharField(max_length=300, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '门店租金资料表',
                'verbose_name_plural': '门店租金资料表',
            },
        ),
    ]
